apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: domain-monitor
  namespace: monitor
  labels:
    release: monitor
spec:
  selector:
    matchLabels:
      app: domain-monitor-web
  namespaceSelector:
    matchNames:
      - monitor
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
