import os

APP_NAME = os.getenv("APP_NAME", "Domain Monitor")
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./domain_monitor.db")
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
SECRET_KEY = os.getenv("SECRET_KEY", "change-me")
CHECK_INTERVAL_SECONDS = int(os.getenv("CHECK_INTERVAL_SECONDS", "60"))
HTTP_TIMEOUT = int(os.getenv("HTTP_TIMEOUT", "300"))
SSL_EXPIRE_WARN_DAYS = int(os.getenv("SSL_EXPIRE_WARN_DAYS", "15"))
WHOIS_EXPIRE_WARN_DAYS = int(os.getenv("WHOIS_EXPIRE_WARN_DAYS", "30"))
NOTIFY_CHANNEL = os.getenv("NOTIFY_CHANNEL", "telegram")
WECHAT_WEBHOOK_URL = os.getenv("WECHAT_WEBHOOK_URL", "")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")
AGENT_NAME = os.getenv("AGENT_NAME", "k8s-local")
AGENT_REGION = os.getenv("AGENT_REGION", "prod-k8s")
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "Admin@123456")
PING_ENABLED = os.getenv("PING_ENABLED", "true").lower() in ("1", "true", "yes", "on")
DAILY_REPORT_ENABLED = os.getenv("DAILY_REPORT_ENABLED", "true").lower() in ("1", "true", "yes", "on")
DAILY_REPORT_TIME = os.getenv("DAILY_REPORT_TIME", "09:00")
DAILY_REPORT_CHANNEL = os.getenv("DAILY_REPORT_CHANNEL", "telegram")
DEFAULT_EXPECTED_STATUS = os.getenv("DEFAULT_EXPECTED_STATUS", "200,301,302")
TZ = os.getenv("TZ", "Asia/Shanghai")
NOTIFY_DEDUP_MINUTES = int(os.getenv("NOTIFY_DEDUP_MINUTES", "10"))
WARNING_FAIL_THRESHOLD = int(os.getenv("WARNING_FAIL_THRESHOLD", "5"))
