from contextlib import contextmanager
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
from config import DATABASE_URL

connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}
engine = create_engine(DATABASE_URL, pool_pre_ping=True, connect_args=connect_args)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)

@contextmanager
def get_db():
    db = SessionLocal()
    try:
        yield db
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()

def _id_col():
    return "INTEGER PRIMARY KEY AUTOINCREMENT" if DATABASE_URL.startswith("sqlite") else "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"

def _bool_default(value: bool):
    if DATABASE_URL.startswith("sqlite"):
        return "1" if value else "0"
    return "TRUE" if value else "FALSE"

def _add_column_if_missing(conn, table: str, column: str, ddl: str):
    try:
        if DATABASE_URL.startswith("sqlite"):
            rows = conn.execute(text(f"PRAGMA table_info({table})")).fetchall()
            cols = {r[1] for r in rows}
        else:
            rows = conn.execute(text("""
                SELECT column_name FROM information_schema.columns
                WHERE table_name=:table
            """), {"table": table}).fetchall()
            cols = {r[0] for r in rows}
        if column not in cols:
            conn.execute(text(f"ALTER TABLE {table} ADD COLUMN {ddl}"))
    except Exception as exc:
        print(f"migration warning: {table}.{column}: {exc}", flush=True)

def init_db():
    idcol = _id_col()
    true_default = _bool_default(True)
    false_default = _bool_default(False)
    stmts = [
        f"""
        CREATE TABLE IF NOT EXISTS users (
            id {idcol},
            username VARCHAR(64) UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            role VARCHAR(32) NOT NULL DEFAULT 'user',
            enabled BOOLEAN NOT NULL DEFAULT {true_default},
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS domain_groups (
            id {idcol},
            name VARCHAR(128) UNIQUE NOT NULL,
            description TEXT DEFAULT '',
            owner_user_id INTEGER,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS domains (
            id {idcol},
            group_id INTEGER,
            domain VARCHAR(255) NOT NULL,
            protocol VARCHAR(16) DEFAULT 'https',
            port INTEGER DEFAULT 443,
            enabled BOOLEAN DEFAULT {true_default},
            remark TEXT DEFAULT '',
            tags TEXT DEFAULT '',
            url_paths TEXT DEFAULT '/',
            expected_statuses TEXT DEFAULT '200,301,302',
            keyword TEXT DEFAULT '',
            check_dns BOOLEAN DEFAULT {true_default},
            check_http BOOLEAN DEFAULT {true_default},
            check_ssl BOOLEAN DEFAULT {true_default},
            check_whois BOOLEAN DEFAULT {true_default},
            check_ping BOOLEAN DEFAULT {true_default},
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS check_results (
            id {idcol},
            domain_id INTEGER,
            agent_name VARCHAR(128),
            agent_region VARCHAR(128),
            domain VARCHAR(255),
            group_name VARCHAR(128),
            url TEXT DEFAULT '',
            url_path TEXT DEFAULT '/',
            is_summary BOOLEAN DEFAULT {false_default},
            status VARCHAR(32),
            http_code INTEGER,
            response_time_ms INTEGER,
            resolved_ips TEXT,
            ssl_expire_at VARCHAR(64),
            ssl_days_left INTEGER,
            whois_expire_at VARCHAR(64),
            whois_days_left INTEGER,
            ping_ok BOOLEAN,
            error TEXT,
            checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS alert_policies (
            id {idcol},
            name VARCHAR(128) NOT NULL,
            group_id INTEGER,
            fail_threshold INTEGER DEFAULT 3,
            recover_threshold INTEGER DEFAULT 2,
            silence_start VARCHAR(16) DEFAULT '',
            silence_end VARCHAR(16) DEFAULT '',
            warning_channels TEXT DEFAULT '',
            critical_channels TEXT DEFAULT '',
            escalation_minutes INTEGER DEFAULT 15,
            escalation_channels TEXT DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS alert_state (
            domain_id INTEGER PRIMARY KEY,
            current_status VARCHAR(32),
            fail_count INTEGER DEFAULT 0,
            success_count INTEGER DEFAULT 0,
            last_alert_status VARCHAR(32),
            last_alert_at TIMESTAMP NULL,
            first_failed_at TIMESTAMP NULL,
            escalated BOOLEAN DEFAULT {false_default},
            last_error TEXT DEFAULT '',
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS maintenance_windows (
            id {idcol},
            name VARCHAR(128) NOT NULL,
            enabled BOOLEAN DEFAULT {true_default},
            start_time VARCHAR(16) NOT NULL,
            end_time VARCHAR(16) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS audit_logs (
            id {idcol},
            username VARCHAR(64),
            action VARCHAR(128),
            detail TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ]
    with engine.begin() as conn:
        for stmt in stmts:
            conn.execute(text(stmt))
        # lightweight migrations for packages already deployed
        for col, ddl in [
            ("tags", "tags TEXT DEFAULT ''"),
            ("url_paths", "url_paths TEXT DEFAULT '/'"),
            ("expected_statuses", "expected_statuses TEXT DEFAULT '200,301,302'"),
            ("keyword", "keyword TEXT DEFAULT ''"),
            ("check_dns", f"check_dns BOOLEAN DEFAULT {true_default}"),
            ("check_http", f"check_http BOOLEAN DEFAULT {true_default}"),
            ("check_ssl", f"check_ssl BOOLEAN DEFAULT {true_default}"),
            ("check_whois", f"check_whois BOOLEAN DEFAULT {true_default}"),
            ("check_ping", f"check_ping BOOLEAN DEFAULT {true_default}"),
        ]:
            _add_column_if_missing(conn, "domains", col, ddl)
        for col, ddl in [
            ("url", "url TEXT DEFAULT ''"),
            ("url_path", "url_path TEXT DEFAULT '/'"),
            ("is_summary", f"is_summary BOOLEAN DEFAULT {false_default}"),
        ]:
            _add_column_if_missing(conn, "check_results", col, ddl)
        group = conn.execute(text("SELECT id FROM domain_groups WHERE name='default'")).fetchone()
        if not group:
            conn.execute(text("INSERT INTO domain_groups(name, description) VALUES ('default', '默认分组')"))
        policy = conn.execute(text("SELECT id FROM alert_policies WHERE name='default'")).fetchone()
        if not policy:
            gid = conn.execute(text("SELECT id FROM domain_groups WHERE name='default'")).fetchone()[0]
            conn.execute(text("INSERT INTO alert_policies(name, group_id, fail_threshold, recover_threshold, escalation_minutes) VALUES ('default', :gid, 3, 2, 15)"), {"gid": gid})
